### ISSUE TITLE
الگوریتم نورونگ

### ISSUE THREAD

**Issue by afshin-ir** [ehsan2022002/VirastarE#3]
<div dir=rtl>
سلام. 

دربارهٔ الگوریتم «نورونگ» که این برنامه از آن استفاده می‌کند، اطلاعاتی لطف می‌کنید؟ با جست‌وجوی کلیدواژهٔ «نورونگ» موفق نشدم چیزی پیدا کنم.

**Comment by ehsan2022002** [comment]
استباه تایپ کرده بودم اسم درست نورویگ
https://norvig.com/
در این پروژه برین
BorzoyaSpell.Suggests.Norvig

**Comment by ehsan2022002** [comment]
https://github.com/ehsan2022002/VirastarE/tree/master/BorzoyaSpell/Suggests/Norvig
